services:
  oracle-free:
    container_name: oracle-free
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: "YourStrongPassword123"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - oracle_free_data:/opt/oracle/oradata
    restart: unless-stopped

    networks:
      - shared-net

networks:
  shared-net:
    external: true
volumes:
  oracle_free_data:

