services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MARIADB_DATABASE: ${MYSQL_DATABASE:-app_db}
      MARIADB_USER: ${MYSQL_USER:-app_user}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-app_password}
      TZ: Africa/Addis_Ababa
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - shared-net

volumes:
  mariadb_data:

networks:
  shared-net:
    external: true
